finnishtransportagency/viite

viite-UI/src/model/ProjectCollection.js
fixes VIITE-1105 bug where link stays green after user chooses not to change geometry that has changed over 5%
clears selection like we do after update
=> VIITE-1105 Links stays green after form is cleared

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
Created an additional case object with the purpose of manipulating the message of the Validation Error.
=> VIITE-1142 -Typo and wrong number in ELY-border validation message

viite-UI/src/view/ProjectChangeTable.js
Added an additional check in order to enable the send to TR button, based on the project status (Incomplete/Error in TR only).
=> VIITE-1113 - "Lähetä muutosilmoitus Tierekisteriin"-nappi on aktiivinen Tierekisteriin jo lähetetyssä projektissa

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
in applychanges added sanity check for changes 1&2. removes changes 1&2 where length changes since it shouldn't
Also fixed one test that had odd change values
=> Viite 1152 lenght test

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/ProjectAddressLink.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLink.scala, viite-UI/src/view/Styler.js
Backend:   
.Added a additional call to the end of each fetch option in order to determine which sequence of addresses (by number and part number) get to have a black line underneath it.
.Added said new parameter to all address objects, that go out to the UI.
UI:
.Reworked the way the LinkProperty Styler handles the previously mentioned adminClassLine in order to depend on the newly created parameter from the backend.
=> VIITE-1117_change_road_styling_of_municipal_roads_based_to_road_addres.road_type_instead_of_vvh

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
Added a small fix to the Check termination validation that it would crash if onlyAdjacents variable is not filled.
Changed the ely border check 2 validation message to print the discontinuity code instead of road part.
=> VIITE-1142 - Changed message object

config/deploy.rb
Deploy script makes symbolic link from “./logs” to “/data1/viite/logs”.
=> VIITE-1309 Logs accessible to monitoring

project/build.scala, src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala, start.sh
added  jetty-jmx for monitoring (download package, needed lines to enable it in code and to start script) tested and it works on windows and *should* work with script as well
=> Viite 1281 monitoring

viite-UI/src/view/ProjectEditForm.js, viite-UI/src/view/ProjectForm.js
There was an unnecessary popup window after pressing cancel button in edit project view when user hasn't made any edits. Now the popup shows up only when there is something to save and user presses cancel button.
=> VIITE-1330 Unnecessary popup window after cancel in edit project view

viite-UI/src/view/ProjectEditForm.js, viite-UI/src/view/ProjectForm.js
Before selection of a new road and canceling immediately in a fresh new project, user wasn't able to select a new road without restarting the project. Also the cancel button worked unlogically. Now these bugs are fixed and hopefully my fixes didn't create new bugs.
=> VIITE-1325 Roads can't be selected after cancel button in an empty project

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala, digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressFiller.scala
Added logging of times different operations take especially in getting the road links. This helps us to identify the slow parts.
Currently the threshold for logging the time is only 1 ms, but later it can be changed to for example 100ms, so that only the slow operations are logged. Now we are interested to see from the logs also if something is working fast.
=> VIITE-1359 Profile code and improve logging

viite-UI/src/view/ProjectChangeTable.js
Added a simple line which let's the user to move the change table only from the header.
=> VIITE-1238 Move the change table only from title bar

viite-UI/src/utils/zoom-levels.js
Changed zoom level for directional arrows from 9 to 11.
=> VIITE-1365 direction arrows are displayed at 50m

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Made a simple method to return the name of the road that is being split.
The origin is firstly the project link, then the road address, if none if found from these 2 sources then we return the original, un-modified value of the name that resides in the project link.
Also corrected a little bug, resulting of calling a .map() method on a empty collection.
Added the road name parameter to the list of outgoing values.
=> VIITE-1361

viite-UI/src/view/RoadNamingToolWindow.js
Added some validations for road naming tool dates. User can't give invalid dates anymore. Day has to be in range 1 to 31 (30 in some months and 28 or 29 in February depending if it is leap year or not). Month has to be in range 1 to 12. There's also changes from VIITE-1373 which added validations for years.
=> VIITE-1374 Incorrect start date gets name tool stuck

viite-UI/src/application.js, viite-UI/src/map/LinkPropertyMarker.js, viite-UI/src/map/ProjectLinkMarker.js, viite-UI/src/model/RoadCollection.js, viite-UI/src/model/SelectedLinkProperty.js, viite-UI/src/utils/LinkValues.js, viite-UI/src/utils/backend-utils.js, viite-UI/src/view/LinkPropertyLayer.js, viite-UI/src/view/MapView.js, viite-UI/src/view/ProjectLinkLayer.js, viite-UI/src/view/RoadLayer3.js, viite-UI/src/view/Styler.js, viite-UI/test/TestHelpers.js, viite-UI/test/integration-tests.html, viite-UI/test/integration-tests/FloatingRoadAddressSpec.js, viite-UI/test/integration-tests/RoadAddressProjectSpec.js, viite-UI/test_data/RoadLinkTestData.js, viite-UI/tmpl/index.html
Adding markers of project link layer to single and double click interactions.
Refactoring of LinkPropertyLayer markers and ProjectLinkLayer markers.
Refactoring on roadLinkData and projectLinkData handling. Now is always called linkData and we don't need to validate it by name, since they are from different layers
=> VIITE-1402 Adding project markers to interactions and refactoring of markers

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala, viite-UI/src/model/ProjectCollection.js, viite-UI/src/utils/backend-utils.js, viite-UI/src/view/ProjectEditForm.js
Added new validation: Viite checks if there is end of road discontinuity on the previous road parts which are not in the project. Side note: Let's try to keep function names as describing as possible. I used a lot of time debugging code because of few functions didn't do what i expected them to do by their names.
=> VIITE-1394 new validation to check the previous road part outside of the project

viite-UI/src/model/ProjectCollection.js, viite-UI/src/view/ProjectEditForm.js, viite-UI/src/view/ProjectLinkLayer.js
Now, when user gives invalid road number for new road (there's already a road with the number), Viite doesn't clear the edit form. It keeps the road information so the user can change the road number and save again with right road number. I also made the code less repeating.
=> VIITE-1410 UUSI action with invalid road number has unwanted behavior

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DiscontinuityTrackCalculatorStrategy.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitter.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
Fix to ProjectLinkSplitter to terminated cases on splitting
Fix to start address of transfer on split delta calculation
Changes in strategy logics to accept Track.Combined values and multiple types of discontinuities
=> VIITE-1430 wrong values on change table for split

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteIntegrationApi.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
Some work with Viite integration API. now it returns all road addresses which are not from future. Not from future = start date is in the past and it has end date in future or the end date is null.
=> VIITE-1379 Viite API returns newest road network which is not from future

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/LinkStatusChangeTrackCalculatorStrategy.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
Strategy is now responsible of defining what addrMValue should use, start or end.
=> VIITE-1525_wrong_aet_values_after_siirto_and_uusi_actions

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Saving history links when we have changes in addresses and using the unchanged operation in project
=> VIITE-1171 - Adding history to unchanged addresses 

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
Previous Tomi PR: 
Fixed road address find so that right road(s) are found. Now discontinuity End of Road is right for ELY border when the same road (same road number) doesn't continue in the next ELY. I'm not sure if the gruntfile.js was supposed to include in the pull request or not but it's there anyway.
=> VIITE-1561 added checks to fix the validations

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadNameDAO.scala
This commit is a request from TR side, because they need to fetch the names changes since created_date instead of valid_from
=> Changes in Integration API to use created_time instead of valid_from

viite-UI/src/utils/LinkValues.js, viite-UI/src/view/Styler.js
Removed mentions of blackUnderline and replaced for a roadTypeId test.
=> VIITE-1573_move_current_blackunderline_logic_to_frontend

viite-UI/src/view/ProjectLinkLayer.js
Users reported that they want ctrl + single click work like ctrl + double click. This makes selecting roadlinks easier. I solved this by making some modifications to selections and calling showDoubleClickChanges instead of showSingleClickChanges if ctrl is pressed.
=> VIITE-1580 (FAST TRACK) Ctrl singleclick works now like ctrl doubleclick

viite-UI/src/view/LinkPropertyLayer.js
Made it so geometryChangedLayer visibility status after a 'roadLinks:fetched' event called after the refreshViewAfterClosingFloating method is set to visible.
=> VIITE-1597 - Peruuta should not let floating be highlighted

viite-UI/src/view/LinkPropertyLayer.js
Made it so geometryChangedLayer visibility status after a 'roadLinks:fetched' event called after the refreshViewAfterClosingFloating method is set to visible.
=> VIITE-1597 - TO QA ENV - Peruuta should not let floating be highlighted

viite-UI/src/utils/date-utils.js, viite-UI/src/view/RoadNamingToolWindow.js, viite-UI/src/view/navigationpanel/ProjectListModel.js
Removed the check of the date + 5 years when dealing with the original date on the link, the +5 years should ALWAYS be from the sysdate.
Added the ability to focus the calendar on the original start date.
=> VIITE-1373_removed_future_date_since_original_start_date

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
1. Previous Link should have calibration point at end if next one have one calibration point at beginning
2. Next Link should have calibration point at beginning if previous one have one calibration point at end
=> VIITE-1758 Starting calibration point is missing in last project link

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
Removed the resetting of SideCode from the ProjectSectionCalculator, before calling a specific strategy's assignMValues
=> VIITE-1775 - Käännetty-check boxin ruksi puuttuu kääntö-projektissa /Käännetty - selected check box is missing in reversing project

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
Added another source for the ely's, project link history is called when the project status is SAVED2TR
=> VIITE-1789 ELY-codes on the Project list after VIITE-1255/ELY-kooditprojektilistalla VIITE-1255 muutosten jälkeen

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/SearchApi.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
VIITE-1813 changing session to transaction because of the use of MassQuery
=> VIITE-1813 problem in SearchAPI with more than 1000 linkIds

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DiscontinuityTrackCalculatorStrategy.scala
- increasing MaxDistanceForSearchDiscontinuityOnOppositeTrack limit to 20 meters.
- Measure of distance between track endpoints is done based on geometry distances, instead of addressMValues in meters
=> VIITE-1812 minor discontinuities on roundabout

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
- revertLinks functions renamed so, that there is no more 4 functions with similar name
- revertLinks fixed so, that it now possible to revert separate links for transferring, unchanged and termination projects
- in case of renumbering always revert the whole road part
=> Viite 1930 revert links

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
- In case of empty vvh links don't update geometries
- Unnecessary (doubled) handling for numbering deleted
=> Viite 1930 revert links when geometry empty

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, digiroad2-api-viite/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AddressLinkBuilder.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectAddressLinkBuilder.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/MunicipalityDAO.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/ProjectAddressLink.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLink.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitionerSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/package.scala, viite-UI/src/view/LinkPropertyForm.js
What was changed:
1. **MTKID**: MtkId is displayed only when selecting a single link.
2. **Kunta**: When several links selected, the municipality name will **only** be displayed if it's the same for all of them.
3. **Tien nimi**: When road name is not defined the label will not be displayed.
=> Viite 1964 add info to right side form

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
VIITE-2026 deducing direction of new links for 2 track roads, when both tracks share the same endpoint
=> VIITE-2026 deducing direction of new links for 2 track roads

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Now _Korja_ button selects all the links that have different road type for the same addresses in both tracks. Even if one of the tracks is still unchanged.
=> VIITE-1899 select links that has different road types

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
Adjust between both tracks should be made according to their "rowchanges" ascending order.
=> VIITE-2061 Dif. Road types mixes the change table on new 2-track roads

viite-UI/src/view/navigationpanel/SearchBox.js
If VKM connection fails, the user will no longer see an "[object Object]" text on the screen, instead, the message "_Yhteys Viitekehysmuuntimeen epäonnistui_" will be displayed.
=> VIITE-1995 added message to warn user that connection to VKM failed

viite-UI/src/view/NodeSearchForm.js
Because of dual points there can be two node points in the same address, but in the list we just show one link.
=> VIITE-2060 Showing unique list of the node point templates.

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/JunctionPointDAO.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/JunctionImporter.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/NodeImporter.scala
-  JUNCTION.END_DATE should be NULL
-  JUNCTION.VALID_TO should be NULL
-  JUNCTION_POINT. VALID_TO should be NULL
-  ROADWAY.VALID_TO and ROADWAY.END_DATE should both be NULL, since this was missing, we were showing points connected to expired / terminated roadways.
=> Viite 2123 junction form displays invalid data

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
Existing valid junction points "can be empty" for yet not expired Junctions.
This can happen if they were already expired in previous iterations for other road parts.
=> VIITE-2304 check existence of empty valid junction points in junction

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala, digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/VVHClientSpec.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectLinkNameDAOSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceTRSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
RoadAddressService does not give default value for vvhFrozen parameter any more.
=> ViiteProperties.vvhRoadlinkFrozen is boolean, not string.

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
When updating Node on a road part that has both single and dual tracks, viite incorrectly places the node point on a single track roadway (results are ordered by track ASC). In some cases the point address then becomes invalid because the point M value does not belong to the possible roadway M values. TR does not find an address for the track 0 and therefore ignores the node point.
Added validation of the M value to be incuded in the roadway that the node point is going to be added.
=> VIITE-2533 Nodes are missing from TR

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
The test "Test changeDirection() When projectLinks are reversed the track codes must switch and start_addr_m and end_addr_m should be the same for the first and last links" fails some times.
This fixes ordering after db fetch to match ordering of projectLinksBefore and projectLinksAfter.
=> A test fix.

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ViiteVkmClient.scala
(katunimi mkstring concatenation replaced with plain " ", instead of previous readily escaped %20, which broke functionality offered by UriBuilder.addParameter)
=> VIITE-2490 Fix katunimi query parameter escape bug when calling viitekehysmuunnin/muunna

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
Viite-2583 Fixed three tests that were failing sometimes because they were executed so fast that the nodes creation time didnt change.
=> Viite-2583 Fixed three tests.

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
Viite-2591 extra calibration points left on the road after automatic reversing caused extra junctionpoints when processing nodes and junctions after sending the project to TR. Now the calibration points are removed when automatic reversing happens.
Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/535/consoleFull)
=> Viite-2591 fix atuomatic road reversing extra junctionpoint bug

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala, viite-UI/src/less/core/buttons.less, viite-UI/src/less/core/forms.less, viite-UI/src/model/ProjectCollection.js, viite-UI/src/utils/backend-utils.js, viite-UI/src/view/FormCommon.js, viite-UI/src/view/ProjectEditForm.js, viite-UI/src/view/ProjectForm.js, viite-UI/src/view/ProjectLinkLayer.js
Viite-2616 move project calculation to its own button and redesign the order in which the buttons (recalculate, show project changes and send to TR) can be pressed during the project.  Replaced validations with only high priority validations (check if notHandled project links exist) when creating or updating project links (normal validation is done when clicking the recalculation button).
=> Viite-2616 move project calculation to its own button 

project/build.scala
[if logback set to print less than info level,] do not list info lines; list only problems, and their summaries, to unclutter the output, and to pinpoint the found problems.
=> Backend tests: output simplification: do not list info lines

viite-UI/src/view/FormCommon.js, viite-UI/src/view/ProjectChangeTable.js, viite-UI/src/view/ProjectEditForm.js, viite-UI/src/view/ProjectForm.js
Project buttons are now shown to user in different stages of the project by setting their disabled and title attributes with jQuery instead of rendering new templates with hardcoded buttons each time.
=> VIITE-2640 refactored the disabling and enabling of the project buttons

viite-UI/src/view/FormCommon.js, viite-UI/src/view/ProjectChangeTable.js, viite-UI/src/view/ProjectEditForm.js, viite-UI/src/view/ProjectForm.js
Prevent user from editing the project links when change table is open. Also disabled Cancel button and Action dropdown if change table is open. After user closes the change table, the buttons and dropdowns become clickable again.
=> VIITE-2641 Disable Save-button when change table is open

digiroad2-viite/src/test/resources/logback.xml
=> Add logback file for tests, to shrink the info lines away from the test set output

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala
Terminated roadway was given a new roadway number (not the same roadway number that project link had) and
roadway points were updated with the project links roadway number.
That caused a bug where obsolete node and junction points weren't terminated because Viite couldn't find the roadway points that the nodes and junction points were on.
=> VIITE-2552 junction and node point expiration bug fix

viite-UI/src/model/RoadCollection.js
fixed a bug where underconstruction links length was not shown on link form.
geometry length was only shown if selectedLinkPropertyToShow.count() === 1. When RoadLinkGroups are formed, underconstruction links are added to the list of groups twice resulting in selectedLinkPropertyToShow.count() === 2 and the geometry length not being shown on the form.
=> VIITE-2663 underconstruction link geometry length not shown on form

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitioner.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitionerSpec.scala, viite-UI/src/model/RoadCollection.js
Fixed a bug where road link duplicates appeared in roadCollection.js roadlinkGroups.
Link groups were partitioned by homogeneous section and if track wasn't same on two different road links then they were put in different groups.
Now that single click selects whole road part regardless of different tracks, we dont have to partition by track anymore.
=> VIITE-2588 fix link group partitioning

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala, digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/MassQuery.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayAddressMapper.scala
Added values startAddrValue and endAddrValue
Apply values only when LinearLocation.validTo is None
Fixed bug with MassQuery in RoadwayDAO.withRoadwayNumbers
Copied debugging for MassQuery from digiroad
Changed exception in RoadwayAddressMapper.mapRoadAddresses to not conflict with API call
=> VIITE-2708 update the API call

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/MassQuery.scala
Changed MassQuery ordering to ensure table is populated during the execution of the query
Alternative solutions would require refactoring of existing MassQuery.withIds uses. This solution works with the existing methods using MassQuery and doesn't cause issues in situations where multiple MassQuery calls are made within a single transaction block.
=> VIITE-2717

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
Removed exception when there are no projects to fetch in atomicallyReserveProjectInUpdateQueue()
=> VIITE-2723

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Refactored notLaskLinkHasChangeofEly validation to use endAddrMValue because for two track roadparts there may be two project links with the same endAddrMValue but different id.
If the last projectLink has change of ELY code and is not a combined track, validate that there are no projectlinks with the same endAddrMValue that don't have change of ELY code.
=> VIITE-2722 Added validation for changing ELYcode on Two Track roadparts

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/NodeDAO.scala
node search tool now finds the last node of the road part even if there is a road part after it. (Before / After value was not needed for this query)
removed obsolete todo comment
=> VIITE-2726 fixed node search tool

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala, viite-UI/src/utils/backend-utils.js, viite-UI/src/view/NodeForm.js
Disable manual editing of junction point addr values if the junction points are located in between two different administrative classes.
Temporarily disabled junction point addr editing if the junction points are located in between two different roadways. (Until VIITE-2524 is done)
Some refactoring
Removed obsolete TODO comment
=> VIITE-2518 added administrative class changing check to junction point validation

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadNetworkDAO.scala
Road_name table contains multiple entries for roadnumbers so there is a need to ensure that only one road_name table entry is selected for each roadnumber in order to avoid duplicates in the roadway network summary.
=> VIITE-2764 date-parameter for /integration/summary API

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Disabled the ability to reserve road part if the project start date is the same as the road parts' start date.
Fixed tests' project start date to be 5 days in to the future compared to the road parts start date.
=> VIITE-2777 temporarily block user from making a "repair project"

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala, digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala, viite-UI/src/utils/LocationInputParser.js
changed regex ordering to enable searching with id's that start with a letter
Added a method to allow searching for a link from complementary link data with the old vvh id
=> Viite-2860 regex and complementary

digiroad2-oracle/sql/test_fixture_sequences.sql, digiroad2-viite/src/test/resources/clear-db.sql
drop complementary_link_table when clearing db
increase roadway_number_seq so tests won't fail after fixture reset test
=> VIITE-2906 fix fixture reset test

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala, digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala
Tiketissä VIITE-2806 toteutettu turhien historiarivien poisjättäminen tapauksessa, jossa roadwayn tiedot eivät ole muuttuneet tavalla, joka vaatisi historian säilyttämisen. Tämän muuttumattoman historiarivin poisjättämistä ei oltu huomioitu uuden roadwayn aloituspäivämäärässä.
=> VIITE-2911 select newRoadway startDate based on changes made

viite-UI/src/view/ProjectEditForm.js
Moved checkInputs call further down so that the save is re-enabled properly
=> VIITE-2895 disable save while checking for existing road name

aws/buildspec.yaml, aws/qa-buildspec.yaml, digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/GraphPartitioner.scala, digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/KGVClientSpec.scala, project/build.scala, sbt.bat, viite-UI/tmpl/index.html
upgraded jts-core to 1.18.2
fixed reference to /bin/sbt-launch.jar
removed reference to deleted RoadLayerSelectionStyle.js
NOTE:
Might have to clear geotools and jts-core from C:\Users\<USERNAME>\.ivy2\cache and building project with ./sbt.bat to download the upgraded version.
=> VIITE-3003 upgraded geotools to version 27.2

project/build.scala
VIITE-3009 Updating: Joda Convert to 2.0.1->2.2.3 (upd Jan 16, 2023), and Joda Time to 2.9.9-> 2.12.5 (upd Mar 31, 2023).
Joda-Time notifies: "Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project."
=> VIITE-3009 Updating: Joda Convert to 2.2.3 and Joda Time to 2.12.5

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ComplementaryLinkDAO.scala, digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/PostGISDatabase.scala, project/build.scala
VIITE-3009 library updates: Updating: Postgis-jdbc ->2021.1.0, and Postgresql -> 42.2.27. Adding Postgis-geometry 2021.1.0.
Postgis-jdbc 2.3.0 to the currently newest ->2021.1.0 (upd Aug 4, 2021), and Postgresql 42.2.5 to the currently newest 42.2 minor -> 42.2.27 (upd Nov 23, 2022). Postgis-geometry 2021.1.0 (upd Aug 05, 2021) added as Postgis-jdbc splitted to Postgis-jdbc, and Postgis-geometry at Postgis-jdbc 2.5.0.
=> VIITE-3009 Updating: Postgis-jdbc & Postgresql, adding Postgis-geometry

viite-UI/src/utils/date-utils.js, viite-UI/src/view/RoadAddressChangesBrowserWindow.js
Browser end-date changed to add 1 day to the end-date input, so that listing shows projects from the date selected as the listing's end-date.
=> VIITE-3046 RoadaddressChangesBrowser to include end date in the listing

viite-UI/src/utils/date-utils.js, viite-UI/src/view/RoadAddressBrowserWindow.js
Added isFinnishDateString function to [date-utils.js](https://github.com/finnishtransportagency/viite/compare/VIITE-3084_date_validation?expand=1#diff-d34e60de5601adc53af074a8fc4faccc86b25d8c49f995c904a6ded7273d8097) to check for correct date format of dd.mm.yyyy with 31 days and 12 months. 
It's now used in validateDate function in [RoadAddressBrowserWindow.js](https://github.com/finnishtransportagency/viite/compare/VIITE-3084_date_validation?expand=1#diff-f40912904efc8cc9ef7b8f3dd1d271c404b7dea77d36e44a69818f8001e0b9cc) to check for correct format of the input string.  
Modified willPassValidations to pass input value as a string instead of date object to validateDate.
Added event listener to clear the date error message when user starts typing the date again.
=> Viite 3084 date validation

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
VIITE-3097 Road address changes browser now returns whole project data for every matching criteria. 
Updated fetchChangeInfosForRoadAddressChangesBrowser to get all road address changes that are linked to projects that fit the search criteria. Replaced multiple if clauses to use Seq and map() to make the dynamic SQL query construction more straightforward.  
In the constructed query RelevantProjects filters projects based on searched criteria and AllRelatedRoadwayChanges fetches all road address changes  related to RelevantProjects.
Added a new unit test to check that the updated fetchChangeInfosForRoadAddressChangesBrowser correctly returns all related road address changes linked to projects. The test checks that, when multiple projects affect the same road part which is searched, the …
=> Viite 3097 road address changes browser modification

viite-UI/src/utils/date-utils.js, viite-UI/src/view/RoadAddressBrowserWindow.js, viite-UI/src/view/RoadAddressChangesBrowserWindow.js
The isFinnishDateString now uses named capture groups in the regex as ESLint warnings suggests.
The switch (targetValue.value) in RoadAddressBrowserWindow.js was still incorrectly using date object as a parameter instead of string value, which is now used with validateDate. (Forgot this in https://github.com/finnishtransportagency/viite/pull/1559 PR).
The validateDate now uses isFinnishDateString to check for the correct format of both startDate and endDate. If startDate is not provided the search is denied with "Alkupäivämäärä on pakollinen tieto" validation warning. Added eventListeners for date inputs to empty the validation warning when typing is continued.
=> Viite 3085 date validation for road address changes browser window

viite-UI/src/view/RoadNetworkErrorsList.js, viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/RoadNetworkValidator.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadNetworkDAO.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/package.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadNetworkDAOSpec.scala
Added three methods to fetch links with extra calibration points from the database: 
1.  fetchLinksWithExtraCalibrationPoints
2.  fetchLinksWithExtraCalibrationPointsWithSameRoadwayNumber
- These are used with roadNetworkErrorWindowContent to show all the found links in the UI for the user
3.  fetchLinksWithExtraCalibrationPointsByRoadPart
- This is used with roadNetworkValidator to validateRoadNetwork before preserving project to DB
- It rises RoadNetworkValidationException: LinkHasExtraCalibrationPoints if links with extra calibration points are found
Added test to test that all three queries work as them should to find extra calibration points
=> Viite-3124 validate calibration point integrity

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/RoadNetworkValidator.scala
- Fixed issue where single roadway points were handled multiple times.
- Junction points that belong to skipped roadway points caused issues and are now expired as part of NodesAndJunctionsService.
- Better logging for risen missingCalibrationPointFromJunction RoadNetw
orkValidationException
=> Viite-3137 & Viite-3139 handling of roadway points

viite-UI/src/view/RoadNetworkErrorsList.js, viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/RoadNetworkValidator.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadNetworkDAO.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadNetworkDAOSpec.scala
Fetching links with extra calibration points on same roadway number now counts the found calibration points correctly. 
Corrected and changed the presentation of data on Road Networks Errors List for better readability.
=> Viite-3134 fix to fetch and list extra calibration points correctly

project/build.scala, viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/util/DatabaseMigration.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
logback-classic  from 1.3.6          to 1.3.14   (Dec 01, 2023, currently newest of 1.3.x series. 1.4.x requires jakarta)
commons-codec    from 1.15           to 1.17.0   (Apr 27, 2024, currently newest)
commons-io       from 2.6            to 2.16.1   (Apr 08, 2024, currently newest)
scala-csv        from 1.3.5          to 1.3.10   (Dec 16, 2021, currently newest, still getting updates?)
flyway-core      from 2.3.1 (@com.googlecode.flyway) to 3.2.1 (@org.flywaydb, Mar 20, 2015, newer versions 4.x and up require code rewrite)
newrelic-api     from 3.1.1          to 8.12.0   (May 24, 2024, currently newest)
slick            from 3.0.0          to 3.0.3    (Sep 11, 2015, further versions 3.1.x and up require whole lib change, or massive DB code rewrite)
jts-core         from 1.18.2 …
=> VIITE-3141 upgrading (mostly minor) libraries:

project/build.scala
Old release info claims "Migration is transparent and automatic on first run of any Flyway command."
=> VIITE-3146 Try updating only Flyway version in this commit.

project/build.scala, viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala, viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala, viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala, viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/SearchApi.scala, viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala, viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ViiteSwagger.scala, viite-backend/api/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala, viite-backend/api/src/test/scala/fi/liikennevirasto/digiroad2/SearchApiSpec.scala, viite-backend/api/src/test/scala/fi/liikennevirasto/digiroad2/ViiteApiSpec.scala, viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala, viite-backend/database/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/APIServiceForNodesAndJunctionsSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectLinkNameDAOSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/ProjectCalibrationPointDAOSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAOSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/integration/Viite_13_218_spec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/process/RoadwayMapperSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/util/DataImporterSpec.scala
Mockito requires to be upgraded/changed, before scalatest, and scalatra can be updated.
So here we go.
MockitoSugar now from under scalatestplus,not anymore part of mockito-core.
=> VIITE-3173 Mockito update

aws/cloud-formation/viite-cost-anomaly-detection.yaml
Changed the AWS Cost Anomaly Detection threshold to trigger alerts only when the daily cost of a service doubles and the cost exceeds 2 dollars over the average cost to avoid unnecessary alerts.
=> Viite-3192 Update AWS Cost Anomaly Detection Thresholds

project/build.scala, viite-backend/conf/env.properties, viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/util/ViiteProperties.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/BaseDAO.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/postgis/DbUtils.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/postgis/GeometryDbUtilsScalike.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/postgis/PostGISDatabaseScalikeJDBC.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/postgis/SessionProvider.scala
1. Configuration for ScalikeJDBC
- Added library dependencies to build.scala
- Added properties for ScalikeJDBC to ViiteProperties.scala and env.poperties for local use
- Implemented database initialization file PostGISDatabaseScalikeJDBC.scala for db connection.
2. Helper methods for DAO classes and session handling
- Modified BaseDAO.scala to have necessary helper methods with ScalikeJDBC
- Created SessionProvider.scala to mimic the Slicks withDynSession implementation
- Created GeometryDbUtilsScalike.scala file that has the DB helper methods for geometry that were incorrectly in the PostGISDatabase file in the Slick version.
- Modified DbUtils.scala to have ScalikeJDBC implementation
=> Viite-3094: Viite-3213 ScalikeJDBC configuration implementation

viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KGVClient.scala, viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
Links from SuRaVage process, but not yet addressed. In addition to UnderConstruction lifecyclestatus, now also Planned, and InUse get their prefill data.
=> VIITE-3229 road number info for SuRaVaGe links

viite-UI/src/application.js, viite-UI/src/view/NodeForm.js
Roles are now fetched before the initialization of NodeForm.js.
=> VIITE-3247 Fix node edit bug

viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/RoadNameDAO.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/RoadNameService.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/JunctionDAO.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/JunctionPointDAO.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/NodeDAO.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/NodePointDAO.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/RoadNameServiceSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/JunctionDAOSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/JunctionPointDAOSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/NodeDAOSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/NodePointDAOSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadNameDAOSpec.scala
Modified following files to use ScalikeJDBC:
- roadNameDAO
- RoadNameDAOSpec
- RoadNameService
- RoadNameServiceSpec
- JunctionDAO 
- JunctionDAOSpec 
- JunctionPointDAO  
- JunctionPointDAOSpec  
- NodeDAO 
- NodeDAOSpec 
- NodePointDAO  
- NodePointDAOSpec 
- NodesAndJunctionsService
- NodesAndJunctionsServiceSpec
withDynTransactionNewOrExisting in NodesAndJunctionsService is not needed with ScalikeJDBC because it handles nested transactions in the same way with the build in transaction method
=> Viite-3094/viite-3217/viite-3300 migrate road name, junction and node related files

viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/PingApi.scala, viite-backend/api/src/test/scala/fi/liikennevirasto/digiroad2/PingApiSpec.scala, viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/BaseDAO.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/ComplementaryLinkDAO.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/LinkDAO.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/MunicipalityDAO.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/PingDAO.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/PostGISUserProvider.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/ProjectLinkNameDAO.scala, viite-backend/database/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala, viite-backend/database/src/test/scala/fi/vaylavirasto/viite/dao/MunicipalityDaoSpec.scala, viite-backend/database/src/test/scala/fi/vaylavirasto/viite/dao/PostGISUserProviderSpec.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectLinkNameDAOSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/CalibrationPointDAOSpec.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAOSpec.scala
- Modified PingAPI and -DAO to use ScalikeJDBC, added test to test the ping
- Modified ComplementaryLinkDAO, MunicipalityDAO, LinkDAO, ProjectLinkDAO and their Spec files to use ScalikeJDBC
- Modified getUser in PostGISUserProvider to return Option as it should
- Modified PostGISUserProviderSpec to use ScalikeJDBC
- RoadLinkService and -Spec to use ScalikeJDBC and removed all methods without use
BaseDAO: 
- Added Select method to return first result
- Added implicit val dateTimeMapper
=> Viite 3094/viite 3215 migrate remaning files in database module

viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
- Project Link Ids are now generated with Sequences.nextProjectLinkId instead of misusing Project Id for them
=> VIITE-3332-fix-to-duplicate-key-error-on-tests

viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/MunicipalityDAO.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/queries.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/NodeDAO.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/util/DataImporter.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
DataFixture migration:
- DataFixture now uses ScalikeJDBC
- runUpdateToDbSlick is now defined in DataImporter as it is the only part of the app that uses the Slick version
- Municipality ids are now fetched from MunicipalityDAO instead of queries.scala as they are not new sequences
NodeDAO cleanup:
- Removed unused table alias
- expireById return type changed to Int instead of Unit
- Removed unused fetchId method
=> VIITE-3094/VIITE-3330 data fixture scalike jdbc migration

project/build.scala
(This is accepted in https://github.com/finnishtransportagency/viite/pull/1679. Here just picked over the current postgis.)
=> VIITE-3015 related build.scala refactoring (Simplifying (sub-)project definitions in build.scala)

viite-backend/conf/env.properties, viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/util/ViiteProperties.scala, viite-backend/database/src/main/scala/fi/vaylavirasto/viite/postgis/PostGISDatabaseScalikeJDBC.scala
Update Scalike to use BoneCp properties so it can be published to Postgis
=> VIITE-3094/VIITE-3337: Update Scalike to use BoneCp properties

viite-UI/src/model/NodeCollection.js, viite-UI/src/view/NodeSearchForm.js
Hot fix to nextRealease:
Nodes and Junctions now appear on the map correctly when the form is opened or map moved. 
- node:fetched event handler is added back to its own event listener to handle the fetched node data separately.
- The moveToLocation function now waits for the node:fetched event to be triggered and resolves the promise with the fetched data.
- This ensures that node:fetched triggers correctly also with fetchedNodes function to load all nodes and junctions, not just the selected ones
- Removed unnecessary spinnerEvent(fetching) as only closing the form happens after its triggered
=> VIITE-3346 nodes and junction wont update when map is moved fix to nextRelease

viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/util/DatabaseMigration.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/util/DataImporter.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/util/RoadAddressImporter.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
- Replaced Slick database operations with ScalikeJDBC equivalents for DataImporter and RoadAddressImporter files. 
-Instead of setting parameters one by one with preparedStatement.setX(), the batch parameters are collected into sequences (Seq[Seq[Any]])
- methods migrate and flywayInit now use the new data source from ScalikeJDBC connection pool
=> VIITE-3304/VIITE-3342/VIITE-3341 scalike jdbc migration of data importer and road address importer files

viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/LinkDAO.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/util/DataImporter.scala, viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/util/RoadAddressImporter.scala
1. Removed fetchHistoryRoadLinksFromKGV as it had no purpose (returned empty map)
2. Refactored RoadAddressImporter with fixes:
- Refactored the order of methods for better readability
- The junction node and roadway points are now handled inserted to db with HandlePoints during the currentMappedConversionAddresses.map instead of collecting params
- def runWithConversionDbReadOnlySession is defined on the class so it can be overridden for tests
- The table name is now converted to SQLSyntax in the fetch queries
- Added fetchByLinkIds to LinkDAO which is used with batchUpdateLinksToDb in RoadAddressImporter
3. Refactored DataImporter:
- Removed runWithConversionDbTransaction as only readonly sessions are needed for conversion database
- Added some comments and some cleanup
=> VIITE-3304/VIITE-3353 remove fetch history road links from kgv and refactoring road address importer 

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
- case _ => is now handled with sqls instead of empty string
=> VIITE-3384-RoadAddressBrowser-null-handling-with-sqls

viite-UI/src/view/ProjectEditForm.js
only listen to input events, this prevents listener from becoming too "noisy".
=> VIITE-3489 fix save button functionality

viite-backend/base/src/main/scala/fi/vaylavirasto/viite/model/ArealRoadMaintainer.scala, viite-backend/base/src/test/scala/fi/vaylavirasto/viite/model/ArealRoadMaintainerSpec.scala
-A specialized trait for EVKs.
-Defining EVKs proper instances (to be probably refined later, as the naming gets fixed by the law) 
-EVK-getters, and EVK-existance check for ArealRoadMaintainer 
-Tests for ArealRoadMaintainer/EVK trait, and fixed EVK objects
=> VIITE-3420 EVK (classes traits objects tests, etc)

viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/AdminApi.scala, viite-backend/viite-main/src/main/scala/fi/vaylavirasto/viite/dynamicnetwork/DynamicRoadNetworkService.scala
Introduce a new parameter to control the update logic. Allows either processing updates day-by-day or in a single batch from the old date to the new date.
=> VIITE-3491 Add a parameter to dynamic link network API

local-dev/idea-run-configurations/Fixture_reset_test.xml, local-dev/idea-run-configurations/Flyway_init.xml, local-dev/idea-run-configurations/Flyway_migrate.xml
Switched from deprecated run-main to the correct runMain task key for compatibility with SBT 1.1.4
=> VIITE-3015 Fix run configurations

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala, viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
VIITE-3322 Fix to a bug where junction points were created at split point of a link:
- Add identifyLinkEndpoints to identify true link endpoints of project links
- Add boolean to findConnectedRoad use only true start/endpoints of a link
- Rename getOrCreateRoadwayPointId to   getIdOrCreateNewRoadwayPoint
- Better alignment of the code
VIITE-3511:
- Add test case for VIITE-3322 bug
=> VIITE-3322/VIITE-3511 add split link check and test for handle junctions and junction points

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/NodeDAO.scala
When a Node was edited, both a history row and a new "current" row were created. As a result, fetching nodes by node number could return multiple rows. The runSelectSingleOption method uses .single(), which expects exactly one result, leading to a TooManyRowsException when multiple rows were returned.
This fix updates the logic to select only the latest node ID from the already ordered query result, ensuring a single result is returned.
=> VIITE-3531 Fix TooManyRowsException in fetchLatestId DAO function

viite-UI/src/view/NodeForm.js, viite-UI/src/view/NodeLayer.js, viite-UI/src/view/RoadLayer.js
Solmut eivät enää liiku itsestään liikuttamisen jälkeen, ja niitä pystyy myös liikuttamaan zoomatessa ilman että ne palaavat takaisin aikaisempiin koordinaatteihin..
=> VIITE-3530: Fix node drift after moving and prevent zoom from resetting node

viite-UI/src/less/site/global.less, viite-UI/src/less/site/map-plugins.less, viite-UI/src/view/CoordinatesDisplay.js, viite-UI/src/view/TileMapCollection.js, viite-UI/src/view/TileMapSelector.js
Jatkoa ticketille VIITE-3541. Pienillllä näytöillä näkyy tuo alapalkki siistinä kun osa kartan asetuksista on siirretty dropdowniin. Myös  "ETRS89-TM35FIN" teksti piilotetaan kun ikkuna pienenee.
=> Viite 3543 responsive toolbar

viite-UI/src/utils/LocationInputParser.js
by allowing digits and letters after the colon in link id regex instead of just digits.
=> VIITE-3550 Fix complementary link id search
