viite-UI/src/utils/LinkValues.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/ProjectLinkLayer.js

Fix: Added proper zIndex to layers to fix selection
Cleanup: Removed duplicated code. Refactored zIndex for layers.

Viite 1130 readding reserved part changes layer incorrectly

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
viite-UI/src/model/ProjectCollection.js

Fix for 5 percentage in geometry length change.
Fix for project creation problem found during testing.

VIITE-1143 Fix for 5 percentage in geometry length change.

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectDaoSpec.scala
viite-UI/src/view/navigationpanel/RoadLinkBox.js

Fixed wrong duplication of new reserved parts for same linkId
Test case

Viite 1153 wrong reserved parts in new road creation

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala

Some code refactoring
Added fix for continuity validator where adjacent road addresses where not being get by correct end point in geometry

Viite 1164 tien loppu validation not working while terminating

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala

Viite 1123 some calibration points not drawing correctly

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala

Fixed logic in project validator for Jatkuuvus EndOfRoad cases which includes:
1.Fixed project validator for Jatkuuvus EndOfRoad cases where we where not consider the terminated road parts
2.Fixed project validator for Jatkuuvus EndOfRoad cases where we where checking the discontinuity from road addresses instead the discontinuity from project link
Refactor is some method validations in ProjectValidator

VIITE-1173

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala

Contains also fix for multiple validation calls in project mode.

Viite 1041 road addresses on suravage links are displayed

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

Added fix for single link in road for tracks validation;
Added one test case for the fix

VIITE-1198 Added fix for single link in road for tracks validation

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala

Fix for the validation when the new_start > new_end

VIITE-1263 apply changes fix

---

viite-UI/src/view/LinkPropertyLayer.js

Added check for applicationModel current action.

VIITE-1285- Käyttäjä ei voi vierittää karttaa valitessaan tuntemattomia

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
fixture-reset.sh

Changes should changes since last change timedate.

Viite 1263 apply changes fix

---

viite-UI/src/view/ProjectEditForm.js

Added the cleaning of the id array when clicking cancel.
(I know this is very small.)

VIITE-1335

---

viite-UI/src/view/ProjectForm.js

Unnecessary popups disabled and some formatting.

VIITE-1313 unnecessary popup after poistu button

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

Added additional logging messages on multiple steps.

VIITE-1334

---

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

Viite 1316 error in viite status adding to viite hotfix

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala

Switched a road where clause from the fetchReservedRoadParts query.

VIITE-1346 - User gets an error message when trying to change the road number of a new road address in a road address project after Viite freeze

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/ProjectLinkPartitioner.scala
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectForm.js

Added a function which cuts the name if it is over 20 characters long and adds "..." in the end. This is because earlier long names broke "Poistu projektista" and "Poista projekti" buttons.

VIITE-1364 Too long project names break Viite

---

viite-UI/src/utils/zoom-levels.js
viite-UI/src/view/LinkPropertyLayer.js

Added a new max zoom setting for calibration points.
When drawing calibration points it will check for that.

VIITE-1366

---

viite-UI/src/view/ProjectEditForm.js

If road number is greater than 70000 that means the road is for pedestrian and thus doesn't need a name.

VIITE-1368 Road name is not obligatory if road number is greater than 70000

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/SearchApi.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteIntegrationApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala

VIITE-1359 profile code

---

viite-UI/src/utils/zoom-levels.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/ProjectLinkLayer.js

Changed limit to 1KM, added same limitation to Project mode.

VIITE-1366 - V2 - Etäisyyslukema symbolit näytetään 1 km mittakaavasta alkaen / Calibration point symbols is shown from 1 km scale

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
viite-UI/src/view/navigationpanel/ProjectListModel.js

Optimized road loading and validation. Opening project is now eight times faster (still some loading time though).

VIITE-1367 Opening a project takes very long time

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapper.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapperSpec.scala

Changes to current and history should be independent

Viite 1369 change apply changes batch logic

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

Tests are passing on Jenkins, check build 983.

Viite 1368 1316 fixing road names are not obligatory if road number is above 70000

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala

Tests are passing, check Jenkins build 977.

Viite 1377 splitted link does not find geometry

---

viite-UI/src/view/navigationpanel/ProjectListModel.js

Quick fix for filtering the project list also after sorting.

VIITE-1262 Project list is now filtered also after sorting

---

viite-UI/src/less/site/action-panel.less
viite-UI/src/view/navigationpanel/RoadLinkBox.js

Added new road type to the legend.

Viite-1306 Add roadtype 3 ja 5 to legend

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-UI/src/model/ProjectCollection.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/SplitForm.js

Earlier Viite didn't update the project errors after updating a split link. Now it does :)

VIITE-1389 When saving the split links, VIITE doesn't validate

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala

basically added new try block around execution of VVH query that checks for IO exceptions
also removed duplicated code by creating fetchFeaturesAndLog method which has code that was used in multiple places.

Viite 1393 loggin when vvh is not responding

---

viite-UI/src/model/ProjectCollection.js

User was unable to save unchanged road link at road number 73 and road part number 18. Now it is fixed but some regression testing is needed.

VIITE-1385 Unable to save unchanged roadlinks

---

viite-UI/src/less/core/forms.less
viite-UI/src/view/navigationpanel/ProjectListModel.js

Fixed checkbox css and changed the wording.

VIITE-1259 displaying old projects on the project list

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala

(Cherry picked only the VIITE-1360 changes from the previous joined branch)

VIITE-1360 Remove municipality restrictions from code

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

Viite now fetches also geometry information of complementary road links.

VIITE-1399 reservation of road parts fails

---

viite-UI/src/view/navigationpanel/ProjectListModel.js

Changing start_date to create_date in table model and sorting functions.

VIITE-1405 Create_date in project list instead of project start_date

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ViiteTierekisteriClient.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectDaoSpec.scala
viite-UI/src/utils/LinkValues.js
viite-UI/src/view/navigationpanel/ProjectListModel.js

Tests on jenkins are passing, check build 1012.

Viite 1398 sending to tr status for project

---

viite-UI/src/less/site/action-panel.less
viite-UI/src/view/navigationpanel/ProjectListModel.js

Changed the header name from alkupvm to luontipvm.
Made some small corrections on the sizes of the Project window because of difference in size of the words.

VIITE-1405

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

Problem was not on ajr 1 and 2 cases, but instead it was checking existing Tien Loppu in the lower road part number from the previous parts

VIITE-1421_ajr_1_2_cases_for_1394

---

viite-UI/src/view/TileMapSelector.js
viite-UI/src/view/navigationpanel/ProjectListModel.js

Added a confirmation/warning popup when opening a project on status 9 (SendingToTR).

VIITE-1415

---

viite-UI/src/less/site/asset-form.less
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectChangeTable.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectForm.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/SplitForm.js

Made some more or less trivial fixes to UI based on user feedback. I refactored the code so that there wouldn't be so much duplicate functions or actions. Code should do same stuff but in more compact way now. I also removed some unused functions.

VIITE-1416 Fixes to UI 

---

viite-UI/src/model/ProjectCollection.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectLinkLayer.js

Reverts finnishtransportagency/viite#186

Revert "VIITE-1410 UUSI action with invalid road number has unwanted behavior"

---

viite-UI/src/model/ProjectCollection.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectLinkLayer.js

Let's merge this again to master because we don't have any documentation how the bug happened so it's impossible to fix.

VIITE-1410 UUSI action with invalid road number has unwanted behavior

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

Added ErroredInTR as a editable state.
Created a test for it, checking for all the possible editable tests.

Viite-1443

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

Also refactored MinorDiscontinuity validation.

VIITE-1457 Fixed connectedDiscontinuousLink validation

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
viite-UI/src/less/core/buttons.less
viite-UI/src/model/ApplicationModel.js
viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/navigationpanel/ProjectListModel.js

This includes:
- VIITE-1464
- VIITE-1465

VIITE-1459 US to let user put a road address to floating.

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala

Added Private roads to the list of roads to have a black underline.

VIITE-1307_gray_background_for_roadtype_5_on_the_map

---

viite-UI/src/application.js
viite-UI/src/model/ApplicationModel.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/RoadLayer3.js
viite-UI/src/view/TileMapSelector.js

Added a check for the "Näytä tieosoiteverkko" if is checked, or not in the visibility handler of the roadLayer3 and on the visibilityHandler and the me.redraw and from ProjectLinkLayer.

VIITE-1460_show_the_roads_does_not_work

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
viite-UI/src/view/ProjectForm.js

Replicated parameters on the newLength, newDiscontinuity and newEly fields when generating address part info.
Added a new event to control the disabled state of the Vaara button.

VIITE-1485_user_cannot_make_new_road_address_reservations_after_removing_existing_reservation_from_project

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/LinkStatusChangeTrackCalculatorStrategy.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
viite-UI/src/model/ProjectChangeInfoModel.js
viite-UI/src/model/ProjectCollection.js

Reverted part of changes made in VIITE-1354 which caused this bug. I guess the VIITE-1354 bugs are happening now again. Also did some refactoring/reformatting here and there.

VIITE-1482 Wrong AET value in change table

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/utils/LinkValues.js
viite-UI/src/view/LinkPropertyLayer.js

UI tests are passing and backend tests are passing as well (build 1309).

Viite 1494 user cannot deselect floatings and the form is not updated

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/DefloatMapper.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/FloatingChecker.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
viite-UI/src/model/SelectedLinkProperty.js

Coefficient should be calculated through MValues difference instead geometryLength since we should not trust floating geometry, only its data

VIITE-1491 changed coefficient logic in floating transfer

---

src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala
viite-UI/src/view/TileMapCollection.js

Reverts finnishtransportagency/viite#244

Revert "revert the revert of 1308"

---

viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/LinkPropertyLayer.js

Switched all DIRECT uses of featuresToKeep to its getter and setter methods.
Added a _.cloneDeep on the props variable, for it was changing the values on the featuresToKeep.

VIITE-1494

---

gruntfile.js
src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala
viite-UI/src/view/TileMapCollection.js

Reverts finnishtransportagency/viite#262

Revert "Viite 1308 revert revert"

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala

WARNING: After Sirra and before Tallenna the mAddress values DO NOT add up but after Tallenna the recalculate fixes all the values again.

Viite 1507 2 segments on top of each other + wrong growing direction when made not floating

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/DefloatMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala

Adding validation for starting point to target addresses

VIITE-1508 validation for floatings with wrong order after defloating

---

viite-UI/src/less/site/action-panel.less
viite-UI/src/view/navigationpanel/RoadLinkBox.js

Disabled cut tool with few lines of css. Now user can't click cut tool and "not allowed" cursor is shown when hovering over cut tool.

VIITE-1520 Disable cut tool

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/CommonHistoryFiller.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

This PR contains the tasks:
VIITE-1170 Common history in road address project: terminating road links
VIITE-1171 Common history in road address project: unchanged road links
VIITE-1524 Extra rows, when using the Terminate function

Viite common history ids fixes

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

Now the end date used is the project date instead of the current date.
Unit test added

VIITE-1170 fixing end dates for history links.

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
viite-UI/src/model/ApplicationModel.js
viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/ProjectLinkLayer.js

UI tests are passing:
And backend tests are passing too ( http://172.17.201.56:8888/job/Run%20OTH%20+%20Viite%20Tests/1448/console )

Viite 1529 ui bugs after major refactoring

---

viite-UI/src/view/ProjectEditForm.js

Currently only keyboard combo CTRL+ V (paste) refreshes Tallenna button in form.
Copy - Paste from Mouse should also refresh the save button.

VIITE-1567 copy paste from Mouse should refresh Tallenna button.

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
viite-UI/src/view/navigationpanel/ProjectListModel.js

Project with errors (others than ErrorInViite) should become editable (updated to Incomplete project status) when reopened by user

Viite 1583 User should be able to reopen and edit sending to TR projects

---

viite-UI/src/model/LocationSearch.js

- sort addresses returned by track
- using always first point of geometry

VIITE-93 :

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
viite-UI/src/model/ApplicationModel.js
viite-UI/src/router.js
viite-UI/src/utils/LinkValues.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/TileMapSelector.js

- Hiding suravage links on project link layer
- Disable suravage links toggle button on project link layer.

VIITE-1599:

---

viite-UI/src/model/SelectedProjectLink.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectLinkLayer.js

Clear current selection list after saving
Renamed method

VIITE-1625 Actions have double geometry / toimenpiteellä tuplageometria

---

viite-UI/src/model/SelectedProjectLink.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectLinkLayer.js

VIITE-1625 BASE MASTER Actions have double geometry / toimenpiteellä tuplageometria

VIITE-1625 commit to MASTER branch

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala

Added a sorting element that restored the correct values to the subtraction ahead.
Tests are passing, check build: 26

VIITE-1169 - Common historyn tarkistaminen projektissa: uusi /Common history in road address project: adding a new road links

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala

Tests are passing, check build 39 on jenkins.

Viite 1657 recalculation in two tracks does not adjust addr m values

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
viite-UI/src/model/ProjectCollection.js
viite-UI/src/view/ProjectEditForm.js

Tests are passing, jenkins build number: 58

Viite 1657 recalculation in two tracks does not adjust addr m values v3

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
viite-UI/src/model/LocationSearch.js
viite-UI/src/utils/backend-utils.js

Corrected some filtering details.

VIITE-1642-Implement road address search functionality in Viite UI

---

viite-UI/src/less/site/modals.less
viite-UI/src/view/RoadNamingToolWindow.js

PR for cherry picked commit from VIITE-1671 Linear Location structure version

VIITE-1671 VIITE_OLD Added message at the bottom of the name tool modal

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala

This task includes a fix for VIITE-1728 and VIITE-1729 tasks.

VIITE-1728 and 1729 fixing added projectlinks in delta calculator

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectReservedPartDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectReservedPartDAOSpec.scala

VIITE-1730 transferring road parts
VIITE-1731 fixing history of roadway changes. We don't delete the changes after the project is sent to TR

VIITE-1730 and VIITE-1731 

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
viite-UI/src/utils/LinkValues.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectEditForm.js

Since master already has the Viite-1677 code on it then it was only a matter of adding the 1707 code.

VIITE-1677 VIITE-1707 master road names fixes

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala

This branch includes fix for: 
VIITE-1730 Transfer road part 2 to road part 1 fails
VIITE-1739 Send all roadway rows to TR

Viite fixing change table and rows on roadway_changes

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadNameService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkNameDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadNameDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadNameServiceSpec.scala

Major refactoring on road names handling on Projects

VIITE-1721 and VIITE-1051 road names handling on projects

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAOSpec.scala

Added the filtering for track in the query state.
All tests are green check: http://172.17.201.56:8888/job/Run%20OTH%20+%20Viite%20Tests/258/console

VIITE-1770_discontinuity_changes_for_both_tracks

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala

VIITE-1756 fixing start points for situations when we only have one saved link

VIITE-1756 fixing problems with 2 track new roads

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAOSpec.scala

VIITE-1785 fix tests

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

All tests are passing on Jenkins: /Run%20OTH%20+%20Viite%20Tests/328/console

Viite 1788 in the end of road discontinuity code should be 1

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala

Fixing RoadwayChanges table to handle terminated links with multiple roadway numbers

VIITE-1857 Tierekisteri doesn’t accept action

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadNetworkDAO.scala
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectForm.js

Restricting the length of road number to five, road part number to three and ELY to two characters in input fields.

VIITE-1875 Restricting the length of input fields, VIITE-1877 Fix for SQL

---

viite-UI/src/less/core/buttons.less
viite-UI/src/less/site/modals.less
viite-UI/src/view/navigationpanel/ProjectListModel.js

UI Needs to be verified before merging.

VIITE-1880 refresh button added

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

New message added for viite\package.scala: NewRoadAlreadyExistsMessage

Viite 1387 error message changed for new roads

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/RoadAddressImporter.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataImporterSpec.scala

VIITE-1898 Not generating one extra row for terminated roadways

---

viite-UI/src/view/ProjectEditForm.js

Viite 1885 hide numerointi from action drop down

---

viite-UI/src/view/ProjectEditForm.js

- LOPUSSA field is enabled 
- ALUSSA is disabled for all cases (Janne's specs)
- LOPUSSA field enabled only if project is editable

VIITE-1894 LET disabled fixed

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectReservedPartDAO.scala
viite-UI/src/model/ProjectCollection.js
viite-UI/src/view/ProjectForm.js

Finished: SUCCESS at http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/2/consoleFull

Viite 1879 deletion of reserved and formed parts

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/oracle/MassQuery.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/CalibrationPointDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/LinearLocationDAO.scala

Implemented two fixes for calibration points:
1. Expiring unneeded calibration points when importing changes from project
2. Not showing expired calibration points on map

VIITE-1929 Expiring calibration points

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala

Viite 1893 checks when saving action

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-UI/src/model/ProjectCollection.js
viite-UI/src/view/ProjectEditForm.js

don't deploy this fix before testin'.
Everything seems to work now.

VIITE-1975 numerointi hotfix

---

viite-UI/src/less/site/map-plugins.less
viite-UI/src/utils/LinkValues.js
viite-UI/src/view/RoadLayer.js

- Hover size changed as required
- Link Id replaced with road type
- If a road has no address, display a message, not a form

Viite 1914 hover changes

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

RoadTypes in two tracks should be sequencial

Viite 1899 add validation to parallel tracks should have same roadtype

---

viite-UI/src/view/NodeLayer.js

- Hide the button when node layer shown
- Show the button, when Node layer hided

VIITE-1974 Remove project select button from Node layer

---

viite-UI/src/view/NodeSearchForm.js

-     First row show road address and node name
-     Road includes road number/road part/distance
-     Node type stays as it is now
-     Node name is replaced by node number

VIITE-1982 Node form improvement

---

viite-UI/src/utils/LinkValues.js
viite-UI/src/view/RoadLayer.js

Node data is shown in hoover like this:
- Nimi: (Node name)
- Solmutyyppi: (Node type)
ToDo:
- Code conversions need to be moved from RoadLayer.js (VIITE-1996)

VIITE-1983 Node point hover data changed

---

viite-UI/src/less/core/forms.less
viite-UI/src/less/core/variables.less
viite-UI/src/less/site/asset-form.less
viite-UI/src/view/LinkPropertyForm.js

- Reduced the space between gray text to 4px (it was 8px before)
- Reduced the space between white text to 6px (it was 10px before)

VIITE-1964 space between labels removed

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/NodeDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/NodeDAOSpec.scala
viite-UI/src/view/NodeSearchForm.js

Running tests right now. I'll remove the label when the tests are done.

VIITE-1890 changed start_addr_m for the actual roadway point addr_m

---

viite-UI/images/junction.svg
viite-UI/images/node-sprite-example.html
viite-UI/images/node-sprite.svg

Simplified node sprite svg and updated colors.

VIITE-1978 Node colors

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala

- removed unused out-fields
- no pretty printing for json
- no z-coordinates

VIITE-1987 Smaller VVH responses

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/NodeDAO.scala
viite-UI/src/application.js
viite-UI/src/view/RoadLayer.js

- Junction address to one row
- Node name added

Viite 1981 junction hover

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala

VIITE-1893 change text

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/TrackCalculatorStrategySpec.scala

- When roadway_number changes, we should not add a calibration point

VIITE-2011 fix calibration points recalculation

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayAddressMapper.scala

VIITE-2010 using rounded values instead of "toLong"

VIITE-2010 roadway address mapper fix

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

_newSavedLinks_ are now beeing filtered to include only newLinks. To prevent an existent road part to be removed from the reserved parts in project.

Viite 2035 reserved road part is kept when all links are transferred

---

viite-UI/src/view/navigationpanel/SearchBox.js

Added text information to the user for when the search is running.

VIITE-1995 info text added

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/JunctionPointDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/NodePointDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectLinkNameDAOSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceTRSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala

Reverts finnishtransportagency/viite#619

VIITE-2002r update roadway point id

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala

RoadwayNumbers for New project links should be generated together, if applicable (in the same continuous section)

Viite 2024 problem with roadway number

---

digiroad2-api-common/src/test/scala/fi/liikennevirasto/digiroad2/util/JsonSerializerTest.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/DummySerializer.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kmtk/ChangeInfo.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kmtk/ChangeType.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kmtk/KMTKClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RoadLinkSerializer.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/ChangeTypeSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ApplyChangeInfoProcess.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapper.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/JsonSerializer.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/Dummies.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ApplyChangeInfoProcessSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayChangeInfoMapperSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/StaticTestData.scala

Most of the clean up work is already in kmtk-branch.

VIITE-1947 Cleaned up VVHClient

---

viite-UI/src/view/RoadLayer.js

Hoover is now hidden for links without road address information.

VIITE-2071 Hoover will not be displayed for links without road address

---

viite-UI/src/map/LinkPropertyMarker.js
viite-UI/src/map/ProjectLinkMarker.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/NodeLayer.js
viite-UI/src/view/ProjectLinkLayer.js

Removed markers for unknown roads:
* view mode: (linkProperty layer and nodes and junctions layer)
* project mode

Viite 2073 question marks should not be displayed on unknown roads

---

viite-UI/src/view/NodeForm.js
viite-UI/src/view/ProjectLinkStyler.js

VIITE 2124/VIITE-2127 before after values are wrong in junction and nodepoint forms/change some table headers

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala

Hotfix: Including z-coordinates when returning results

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/ProjectLinkStyler.js

Add blackUnderline as under layer with minor zIndex.
Some refactor.

VIITE-2121 add blackUnderline as under layer with minor zIndex

---

gruntfile.js
project/build.properties
project/build.scala

Last critical changes: 
- Removed unneded open layers in deploy
+Added jar exclusion

Viite 1954 library updates with devtest integration

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitioner.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitionerSpec.scala
viite-UI/src/less/site/map-plugins.less
viite-UI/src/model/ApplicationModel.js
viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/router.js
viite-UI/src/utils/LinkValues.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/TileMapSelector.js

Merged VIITE-2075 in this branch to help testing.

VIITE-2174 hotfix to editable roads in project mode

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala

Notice that roadways with end dates in the future should be included in the current road address network.

VIITE-2198 Excluding roadways with end date from ui.

---

conf/dev/revision.properties
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/LinkDAO.scala
revision.properties

Latest link date is checked also from the frozen links.

VIITE-2199 Showing the date of data correctly.

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayAddressMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

We should update calibration points after roadwaypoints update and BEFORE handling of junction points method

Viite 2202 infinite recursion case

---

viite-UI/src/view/ProjectLinkLayer.js

In project it is now possible to select unaddressed under construction links but not addressed

VIITE-2208 Prevent selection of unreserved addressed under construction links

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala

Not joining continuous + continuous (parallel link) together

VIITE-2216 join rows that are not parallel Discontinuity

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala

all tests passing at: http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/141/console

Viite 2246 wrong calibration points when reversing

---

viite-UI/src/less/core/icons.less
viite-UI/src/less/core/variables.less
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectChangeTable.js

and shown only for the reversed rows. Reversed check mark size increased on the form.

VIITE-2241 Change table reversed check mark is now bigger

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

Adding Left track first instead of Right track, should close the form even when not calculated properly, due to missing opposite track

VIITE-2281 Problem in adding Left track first instead of Right track

---

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefaultSectionCalculatorStrategySpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala

Implemented unit tests. The actual problem was fixed in another issue.

VIITE-2282 Starting point when multiple discontinuities

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala

tests passing at: http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/194/consoleFull

VIITE-2296 Prevent user discontinuity updates in case the links are not calculated

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala

[Tests **OK**] http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/211/consoleFull

VIITE-2311 hotfix to expiration of node points when road type changes

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala

completely unchanged single roadway with Unchanged + Transfer links should not create 2 new roadways for same roadway number

Viite 2299 roadway without modifications should not be splitted

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala

[Tests **OK**] http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/210/consoleFull

VIITE-2312 junction templates on roads under 70000 only

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/NodePointDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLink.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectChangeFiller.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayAddressMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

all tests passing at: http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/215/console

Viite 2336 check project calculator to have same rounding adjustments as roadway address mapper

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/CalibrationPointDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/CalibrationPointsUtils.scala

- Updating of calibration point when we should expire old and create new
- One fetch without valid_to is null restriction
- One fetch that restricts also with roadway point id and cannot find old calibration point that is in different address

VIITE-2345 Fixed three problems with calibration points.

---

conf/dev/digiroad2.properties
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/authentication/TestUserSupport.scala

This change is needed so that you can use idea frontend debugger

Development login with development property file instead of cookie

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/authentication/JWTAuthentication.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala

Assuming that the username comes in "x-amzn-oidc-identity" -header.

VIITE-2288 JWT user authentication.

---

conf/ci-vahti/digiroad2.properties
conf/dev/digiroad2.properties
conf/production/digiroad2.properties
conf/production2/digiroad2.properties
conf/staging/digiroad2.properties
conf/test/digiroad2.properties
conf/testing/digiroad2.properties
conf/testing2/digiroad2.properties
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/SearchApi.scala
digiroad2-api-viite/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ViiteProperties.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala

Avoiding writing in disk in AWS Fargate to make things simpler.

VIITE-2373 Disable caching functionality.

---

project/build.scala

more info at https://wiki.osgeo.org/wiki/SAC:Repo

osgeo path have been changed

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefaultSectionCalculatorStrategySpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala

[Tests **OK**] http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/286/consoleFull
- Current changes also fix **VIITE-2378**. Tested it and moved it to `code review` column in `jira`

VIITE-2377 created mismatching tracks exception

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/NodeDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadNameDAO.scala

for the new rows of the node and road_name -tables.

VIITE-2381 Letting the database set the valid_from value automatically

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala

Tests **OK** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/304/consoleFull).

VIITE-2392 coordinates of node points and junction points

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayAddressMapper.scala

Tests **OK** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/312/consoleFull).

VIITE-2393 addresses are now calculated after rp and cp updates

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/NodeImporter.scala

Node points should have valid_to as the same end_date as its node

Viite 2311 node point missing at roadtype change

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala

* Node points on track two are now being expired as expected.
Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/341/consoleFull).

Viite 2407 expire node points on track two

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/JunctionDAO.scala

Tests **OK** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/351/consoleFull).

VIITE-2369 fetched junctions by bounding box

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala

Tests **OK** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/352/console).

VIITE-2413 hotfix for bad error message

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/JunctionDAO.scala

Tests **OK** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/356/consoleFull).

VIITE-2369 missing clause to filter out templates

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultTrackCalculatorStrategy.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DiscontinuityTrackCalculatorStrategy.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/LinkStatusChangeTrackCalculatorStrategy.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala

Tests **OK** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/360/consoleFull).

VIITE-2414 hotfix for roadway sections

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala

1. _Temporarly Not In Use_ = **4**;
2. _Expiring Soon_ = **5**;

VIITE-2390 added two new CONSTRUCTION TYPE values

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
gruntfile.js

Tests **OK** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/375/consoleFull).

VIITE-2440 missing junction condition for different parts intersection

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/Dummies.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala

VIITE-2495_fix_search_against_digitizing

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala

Tests **Ok** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/407/consoleFull).

Viite 2503 junction template links empty

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionRoadway.scala

Tests **Ok** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/412/consoleFull).

VIITE-2371 er case

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/JunctionPointDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

Test covers case where junction is missing in connection point.
There is no test for case where there is junction in connection point.

viite-2424 validate new projectlink

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
viite-UI/src/model/LocationSearch.js

Fix search for linkid and mtkid and for cases where road contains many links

VIITE-2514 fix search

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionRoadway.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala

**Update**: Allowed new links to be added in two track roads after split implementation.
Tests **Ok** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/421/consoleFull).

VIITE-2521

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala

Tests **Ok** [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/423/consoleFull).

Viite 2511 order links from different parts

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala

Handle a special case when calculated nodepoint resides on a roadway that does not have a junction on it.

VIITE-2533 Node point on roadway without junction

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ViiteProperties.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

Merged current master. 
Can transfer and reverse two-track roads with 90-deg turns.
Know issue with handling roadwaynumbers.
Jenkins tests ok.

Pm1 fixes for long road 40921 1 with track number changes and 90deg turns

---

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/475/consoleFull)

Viite-2550 update test

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala

Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/490/consoleFull)

Viite-2542 Obsolete junction not removed after road address change

---

viite-UI/src/model/ApplicationModel.js
viite-UI/src/view/InstructionsPopup.js
viite-UI/src/view/ScaleBar.js
viite-UI/src/view/WorkListView.js
viite-UI/src/view/navigationpanel/RoadLinkBox.js
viite-UI/src/view/navigationpanel/SearchBox.js

Refactored div self closing tags

Viite-2566 jQuery div self closing tag refactoring

---

viite-UI/src/utils/LinkValues.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectLinkLayer.js

Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/514/consoleFull)

VIITE-2568 Couple of UI bug fixes

---

viite-UI/src/view/RoadLinkStyler.js

Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/517/consoleFull)

removed border rules styling from unaddressed links

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala

Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/519/consoleFull)
Fixed one test regarding termination.

Viite 2574 roadway history row bug fix

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala

Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/521/consoleFull)

Viite-2574 Fixed a bug where terminated roadway would get wrong discontinuity code.

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-viite/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala

* converted administrativeClass to roadtype, added administrative type to integration apis where roadtype is also presented.
* fixed test, modified identifiers
* Refactoring
* More refactoring

Viite-2568 integration api fix (#1023)

---

viite-UI/src/view/ProjectForm.js

Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/526/consoleFull)
Works on both Chrome and Firefox now.
[Old ticket about this](https://extranet.vayla.fi/jira/browse/VIITE-1358)

Viite-1358 Fixed autocomplete on project form when using Chrome. 

---

aws/task-definition/dev/task-definition.json
conf/env.properties
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/SearchApi.scala
digiroad2-api-viite/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ViiteProperties.scala

https://extranet.vayla.fi/jira/browse/VIITE-2455
Remove basic authentication from use in APIs that Viite offers to other applications.

Viite-2455 Remove basic authentication

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

Tests OK [here](http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/533/consoleFull)

Viite-2591 fix automatic road reversing track code bug on two track roads

---

viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/ProjectEditForm.js

added geometry length to link property and project edit forms, added addr length to link property form

Viite-2589 add geometry length and roadaddress length to link property form

---

src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala

remove redundant headers to fix loading of background maps

Viite-2605 remove redundant headers

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/RoadLayer.js

single click starts a fetch process of whole roadpart and updates selected section after fetchprocess is done.

Viite-2588 single click on roadlink selects whole roadpart (homogeneous section)

---

aws/task-definition/dev/task-definition.json
conf/env.properties

use https connection to OAG instead of http

Viite-2606 use https connection to OAG instead of http

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala

fix roadway history rows when reversing road + renamed few variables

Viite-2596 fix roadway history rows when reversing road

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala

Fix existing history roadway expiring bug

Viite-2598 Fix existing history roadway expiring bug

---

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala

Fix occasional test fail in RoadwayFillerSpec

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/Dummies.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala

Assign correct end date and administrative class to history row.
Fix tests.

Viite 2612 fix wrong end date on history row

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/Dummies.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala

Viite-2597 fix continuity code on change table

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala

Viite 2614 Yhteenvetotaulukko ei muodostu oikein kun on siirretty tieosa toiseen jossa on kääntötoimenpide.

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ViiteTierekisteriClient.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceTRSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ViiteTierekisteriClientSpec.scala
viite-UI/src/model/ProjectCollection.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectForm.js

Lokaalitestisetti läpi (2021-09-16) commit c560bdbm jälkeen.

Viite 2608/viite 2618 tierekisteri call removal  from between button click and jalkikasittely

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceTRSpec.scala
viite-UI/src/model/ProjectCollection.js
viite-UI/src/utils/LinkValues.js
viite-UI/src/view/ProjectChangeTable.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectForm.js
viite-UI/src/view/SplitForm.js
viite-UI/src/view/navigationpanel/ProjectListModel.js

Viite 2608/viite 2619 tierekisteri call removal  removing obsolete project states

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala

replace normal validation with high priority validation when reverting changes to projectlink(s)

Viite-2631 replace normal validation with high priority validation when reverting changes to projectlink(s)

---

viite-UI/src/view/ProjectEditForm.js

refresh view when recalculate button is clicked  (after backend is done recalculating.)

Viite-2626 refresh view after recalculation

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-UI/src/model/ProjectChangeInfoModel.js
viite-UI/src/view/ProjectChangeTable.js

removed recalculation and validation from the process of getting change table data.

Viite-2627 remove recalculation and validation from the process of getting change table data.

---

viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectChangeTable.js

Disable recalculate and changes buttons if project change table is open.

VIITE-2635 Disable buttons if change table is open.

---

viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectForm.js

added titles to disabled project buttons. The title describes to the user why the button is disabled

Viite-2628 add descriptive title to disabled project buttons

---

viite-UI/src/view/ProjectChangeTable.js

Disable recalculate and changes button and set tooltips if changetable is open.

VIITE-2635/2628 Disable buttons and set tooltips if changetable is open

---

viite-UI/src/less/site/asset-form.less
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/SplitForm.js

Added info text to guide user to recalculate the project link m values after all links are handled (no high priority errors returned after saving project links)

VIITE-2639 added info text after all links are handled

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala

VIITE-2634 Fix reversion of a new link on reversed road which caused changetable to form incorrectly.

VIITE-2634 Handle different link status reversal in changetable.

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala

Added tests for this and other roadway change definitions. 
Refactorings to RoadwayFiller.

Viite-2600 Admin class change does not produce history row correctly

---

viite-UI/src/model/ProjectCollection.js
viite-UI/src/view/ProjectChangeTable.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectForm.js

disable recalculate button when user recalculates project links and enable it when new changes are saved to the project links

VIITE-2657 disable recalculate button after recalculating

---

viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/ProjectEditForm.js

VIITE-2588 fix build

---

ci/pipeline/deploy_production
ci/pipeline/deploy_staging
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ViiteProperties.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ViiteVkmClient.scala
src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala

Add support for proxy to vkmClient
Add the right proxy host and port in getHttpClient

VIITE-2651 fix vkm api connection when using proxy

---

viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/MapView.js
viite-UI/src/view/ProjectEditForm.js

VIITE-2664 add ctrl click (ability to multiselect single links) to viewing mode

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/DataImporter.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/RoadAddressImporter.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataImporterSpec.scala

and renaming roadwayResetter function to roadwaySequenceResetter, as that is what it does.

Added proceeding prints to Initial import scripts,

---

viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyLayer.js

Fixed a bug where if the last selected link was deselected, all links would stay pale instead of returning to deep colored.
Fixed a bug where selected links did not stay as selected when the map was moved and more links were selected.
Grunt tests OK

VIITE-2664 bug fixes

---

viite-UI/src/model/ProjectCollection.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/navigationpanel/ProjectListModel.js

Fix eslint warnings

---

viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyLayer.js

Fix bug where two road links share the same link id and and ctrl-clicking one of those road links would select both road links.

VIITE-2664 shared linkid bug

---

aws/local-dev/postgis/docker-compose.yaml
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/integration/Viite_13_218_spec.scala
viite-UI/src/application.js
viite-UI/src/less/core/forms.less
viite-UI/src/model/RoadCollection.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/NodeForm.js

VIITE-2518 add constraints to junction point addr update

---

viite-UI/src/less/site/project-change-table.less
viite-UI/src/view/ProjectChangeTable.js

VIITE-2615 add project start date to change table header

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala

Fix erroneous isBetweenMeasures(Double, Double) (--AddrMValue -> --MValue).
Also commentaries to that, and sibling functions.

VIITE-2705 Fix /search/road_address/ API filtering logic:

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
viite-UI/src/view/ProjectChangeTable.js

Backend: changeTable is now recalculated for every projectState except Accepted, InUpdateQueue and UpdatingToRoadNetwork
UI: add check to a condition

VIITE-2694 fix changeTable open bug

---

viite-UI/src/view/ProjectForm.js

Project with status:  10: "Odottaa tieverkolle päivittämistä", 11: "Päivitetään tieverkolle" OR 12: "Hyväksytty", will have only the changes button clickable.
Refactoring: moved button logic away from nextStage() so the code is cleaner and easier to read.

VIITE-2707 Fix uneditable project status buttons bug

---

viite-UI/src/view/RoadLayer.js

Removed duplicate code and made code easier to read

VIITE-2588 SingleClick selects whole road part

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

Project state was not updated from withDynSession block which threw an exception and left the project state in wrong state

VIITE-2648 Project state bug fix

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala

Fixed validation for splitted projectlinks.

VIITE-2696

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala

Fix to validation to allow length change on termination.

VIITE-2695

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala

Fixed existing address length changed in calculation.

VIITE-2710

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
viite-UI/src/view/FormCommon.js

added temporary validation to check that there are no reversed links in project
disabled reverse button

VIITE-2714 disabled road reversing feature

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala

Fixed a bug where dual roadway point was handled incorrectly when dual roadway point was no longer needed at that point. When updating the dual roadway point to be a regular roadway point, the roadway point got wrong addressM which resulted in a extra junction point with wrong address in the UI.
Renamings
Two tests for dual roadway point addrM handling

VIITE-2759 fix dual roadway point handling

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

added a test case for that function as well

VIITE-2685 fix checkForInvalidUnchangedLinks validation function

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

Fix linearlocations when AgainstDigitizing has been splitted.

VIITE-2781

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala

Fix change table having extra rows with New links

VIITE-2779

---

viite-UI/src/view/LinkPropertyForm.js

VIITE-2801 fix roadName field when road doesn't have a name

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
viite-UI/src/less/core/buttons.less
viite-UI/src/model/ProjectCollection.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/navigationpanel/ProjectListModel.js

only fetch active projects unless user has ticked the "fetch all projects accepted to road network" box
added a spinner effect to the sync button

VIITE-2824 active projects are fetched faster now

---

viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/RoadLayer.js

no-whitespace-before-property
no-useless-concat

VIITE-2808 fix eslint warnings

---

viite-UI/src/view/LinkPropertyLayer.js

VIITE-2784 double click also shows direction marker now

---

aws/task-definition/dev/dev-task-definition.json
conf/env.properties
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ViiteProperties.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AwsService.scala
project/build.scala

dev and local environment changes.
integration api /road_address is now using the s3 bucket solution to avoid the api gateway restrictions

VIITE-2771 avoid api gateway restrictions

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

VIITE-2820 Remove extra roadpart reservation after numbering

---

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadNameDAOSpec.scala
viite-UI/src/view/RoadAddressBrowserWindow.js

VIITE-2835 small fix for notification text

VIITE-2856 unit test for fetching road names for road address browser

---

viite-UI/src/view/RoadAddressBrowserWindow.js

added option to use raw data to form workbook

VIITE-2835 fix excel date bug

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

VIITE-2820 Numbering releases reservation if not all links are selected

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/navigationpanel/RoadLinkBox.js

VIITE-2862 Fix withDynSession to fetchPrefill()

---

viite-UI/src/less/site/action-panel.less
viite-UI/src/view/RoadAddressBrowserWindow.js

VIITE-2867 faster implementation for creating the results table

---

viite-UI/src/view/RoadAddressBrowserWindow.js

VIITE-2867 refactored to more readable code

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayDAOSpec.scala
viite-UI/src/view/RoadAddressBrowserWindow.js

added administrative class to class TrackForRoadAddressBrowser

VIITE-2869 convert road address browser target "Roads" to "Tracks"

---

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayDAOSpec.scala

rename track section query test
new unit test for road part query

VIITE-2873 unit test for road part query

---

viite-UI/src/utils/date-utils.js
viite-UI/src/view/RoadAddressBrowserWindow.js

adjust datepicker year range from 1950-2050 to 1900-2050

VIITE-2877 adjust date picker year range

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala

VIITE-2897 removed unnecessary fetch with vvh_id

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/SearchApi.scala
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/LinearLocationDAO.scala

Added parameter mapping for various API calls
Fixed massQuery calls with linkId

VIITE-2901 added optional parameter mapping for LogUtils

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

VIITE-2876 refactor checkRemovedEndOfRoadParts

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala

Move VIITE-2911 to QA

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala

Move VIITE-2876 to QA

---

viite-UI/src/model/ProjectCollection.js

VIITE-2875 Fix cancel-case from popup when new link is given length >20%

---

viite-UI/src/model/ApplicationModel.js

Cleaned and refactored ApplicationModel.js file
var -> let/const and removed unused code

[Cleaning/Refactoring]

---

viite-UI/src/view/ProjectLinkLayer.js

unaddressed links with different administrative classes can be selected together

VIITE-2945 fix ctrl click selection in project mode

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala

* VIITE-2961 refactored roadname join to exclude duplicates
* VIITE-2961 fix typo
* VIITE-2961 refactored to use coalesce
* VIITE-2961 fix grammar

Push to QA

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala

VIITE-2957 change length change error to warn

---

digiroad2-api-viite/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala

Hmph, IntegrationAPI bulletproof test fixes were blatantly missing.

VIITE-2982 - IntegrationAPI bulletproof - test fixes

---

viite-UI/src/less/site/modals.less
viite-UI/src/utils/date-utils.js
viite-UI/src/view/RoadAddressBrowserWindow.js

z-index fix so that the overlays are the top most elements on the screen when displayed
added space to string

VIITE-2996 fix date validation

---

viite-UI/src/view/RoadAddressChangesBrowserWindow.js

Fix start date and end date to validate chronologically

VIITE-3019 fix RoadaddressChangesBrowser date validation

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala

Head of empty list -error in ely validation

VIITE-3033 head of empty list error

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/integration/Viite_13_218_spec.scala
viite-UI/src/model/ProjectCollection.js

added link ids to ValidationErrorDetails class so that project error always has the link id list.

VIITE-2960 fix link id list bug

---

viite-UI/src/view/ProjectForm.js

Projekti-formin päivämääräkenttä korjattu ottamaan vastaan vain numeroita ja päivämäärää merkitseviä välimerkkejä
Testattu

VIITE-3036 projectform date validation

---

package.json

VIITE-3063 update sheetjs library version form 0.18.5 to 0.20.0

---

viite-backend/api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
viite-backend/api/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/APIServiceForNodesAndJunctions.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/NodesAndJunctionsService.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/JunctionDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/LinearLocationDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/NodeDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/APIServiceForNodesAndJunctionsSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/JunctionDAOSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/LinearLocationDAOSpec.scala

VIITE-3055
Rajapinta solmuille ja liittymille

VIITE-3055 nodes and junctions interface

---

viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

avoidRestrictions for nodesAndJunctionsAPI

VIITE-3071 avoidRestrictions for nodesAndJunctionsAPI

---

viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala
viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala
viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/AwsService.scala

(And sibling-nearly-bulletproofed experimental version. And comment tweakings.)

VIITE-3050 integration/road_address API not ever returning

---

viite-UI/src/view/RoadAddressBrowserWindow.js
viite-UI/src/view/RoadAddressChangesBrowserWindow.js

Corrected date validation message to "pp.kk.vvvv" in RoadAddressBrowserWindow.js and RoadAddressChangesBrowserWindow.js.

Corrected date validation message to "pp.kk.vvvv"

---

viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
viite-backend/viite-main/src/main/scala/fi/vaylavirasto/viite/dynamicnetwork/DynamicRoadNetworkService.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/ProjectReservedPartDAOSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayDAOSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/integration/Viite_13_218_spec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/util/DataImporterSpec.scala

Uudelleennimeämisiä: "---RoadAndPart" -> "---RoadPart"

VIITE-3102 RoadPart related renaming

---

aws/cloud-formation/viite-cost-anomaly-detection.yaml

Added cloudFormation template for cost anomaly detection
- Daily checks if costs go over 15% of the expected cost
- One notification per day for all daily anomalies that exceed the 15% threshold

Viite 3184 aws notifications for cost anomalies

---

viite-backend/viite-main/src/main/scala/fi/vaylavirasto/viite/dynamicnetwork/DynamicRoadNetworkService.scala

Make sure that the Tiekamu change set has actual changes in it.

VIITE-3212 add validation

---

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectReservedPartDAO.scala

- Optimized formedByIncrease with usage of CTEs.
- Added Scaladoc for the method
- Added time logger info of formedByIncrease and formedByReduction to include which one is logged.

Viite-3237: Optimized formedByIncrease with usage of CTEs.

---

viite-UI/src/view/RoadAddressBrowserWindow.js
viite-UI/src/view/RoadAddressChangesBrowserWindow.js

VIITE-3256 fix to bug where dates where handled incorrectly for excel file imports

VIITE-3256 fix to bug where dates where handled incorrectly for excel file imports

---

viite-UI/src/view/RoadAddressBrowserWindow.js
viite-UI/src/view/RoadAddressChangesBrowserWindow.js

Fixed  issues with opening and closing of the browser windows after errors.

Viite 3188 road address and address changes browser windows bug fix

---

viite-backend/database/src/main/scala/fi/vaylavirasto/viite/postgis/MassQuery.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/LinearLocationDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/LinearLocationDAOSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayDAOSpec.scala

Modified LinearLocationDAO, LinearLocationDAOSpec, RoadwayDAO, RoadwayDAOSpec and MassQueryto use ScalikeJDBC

Viite 3094/viite 3216 scalike jdbc roadway dao linear location dao and mass quer

---

viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/Sequences.scala
viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/queries.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/CalibrationPointDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectCalibrationPointDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayPointDAO.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/ProjectCalibrationPointDAOSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/ProjectDAOSpec.scala

Migration of files:
- CalibrationPointDAO and Spec
- ProjectDAO and Spec
- ProjectCalibrationPointDAO
- RoadwayPointDAO

VIITE-3094/VIITE-3218 Migration of files:

---

viite-backend/base/src/main/scala/fi/vaylavirasto/viite/model/AddrMRange.scala
viite-backend/base/src/test/scala/fi/vaylavirasto/viite/model/AddrMRangeSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/integration/Viite_13_218_spec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala

Erityistoiveissa katselmoinnin yhteydessä funktioiden nimien pohdinta.
Move toiminee tuollakin nimellä. Mutta sit tuo toinen.
Oli alunperin työnimellä reverseMove, mutta en ollut tyytyväinen siihen. Lienekö tähänkään. Keskustelua, ehdotuksia?

VIITE-3319 addrMRange.move and .mirrorBy

---

viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/PingApi.scala
viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-backend/api/src/test/scala/fi/liikennevirasto/digiroad2/ViiteApiSpec.scala
viite-backend/conf/env.properties
viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
viite-backend/database/src/main/scala/fi/liikennevirasto/digiroad2/util/SqlScriptRunner.scala
viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/PingDAO.scala
viite-backend/database/src/main/scala/fi/vaylavirasto/viite/postgis/GeometryDbUtilsScalike.scala
viite-backend/database/src/main/scala/fi/vaylavirasto/viite/postgis/PostGISDatabaseScalikeJDBC.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectLinkNameDAOSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/integration/Viite_13_218_spec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/util/package.scala

1. Modified remaining files to use Sca
likeJDBC
2. Removed runWithFutureTransaction an
d its usage as it was not necessary

VIITE-3094/VIITE-3327 remaining files to code review

---

viite-backend/conf/env.properties
viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/PostGISUserProvider.scala
viite-backend/database/src/test/scala/fi/vaylavirasto/viite/dao/PostGISUserProviderSpec.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

- Changed the PostGISUserProvider name back for now
- Removed unnecessary logging

VIITE-3094/VIITE-3338: Change the PostGISUserProvider name back for now

---

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/util/NodeImporter.scala

- Note: Refactored the order of methods to be more readable

VIITE-3304/VIITE-3344: Migrate NodeImporter to use ScalikeJDBC

---

viite-backend/api-common/src/main/scala/fi/liikennevirasto/digiroad2/authentication/JWTAuthentication.scala
viite-backend/api-common/src/main/scala/fi/liikennevirasto/digiroad2/authentication/UnauthenticatedException.scala
viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/PostGISUserProvider.scala
viite-backend/geo/src/main/scala/fi/liikennevirasto/digiroad2/user/User.scala

- Add error handling for database query errors
- Implement logging for authentication failures
- Add viewer permission fallback for database errors
- Document authentication flow

VIITE-3363: Add error handling and logging for user authentication

---

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/ProjectDAOSpec.scala

- Fixed nested array bug on the updateProjectElys method
- Modified toProjectMap method to read only single arrays for elys as nested arrays are incorrect data structure
- Created test for ely update method

VIITE-3390 fix to nested array with elys bug

---

viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/PostGISUserProvider.scala

Add copy of userProviderDAO with old name (PostGISUserProvider) for backward compatibility

VIITE-3386: Add copy of userProviderDAO with old name

---

viite-backend/base/src/main/scala/fi/vaylavirasto/viite/model/ArealRoadMaintainer.scala
viite-backend/base/src/test/scala/fi/vaylavirasto/viite/model/ArealRoadMaintainerSpec.scala

VIITE-3417 ArealRoadMaintainer base trait

---

aws/cloud-formation/viite-create-ecr-repository.yaml

- Changed the new SSO role for Cross Account Push

VIITE-3490 Update new SSO Role to ECR cloudformation template

---

viite-backend/base/src/main/scala/fi/vaylavirasto/viite/model/ArealRoadMaintainer.scala
viite-backend/base/src/test/scala/fi/vaylavirasto/viite/model/ArealRoadMaintainerSpec.scala

-A specialized trait for ELYs.
-Defining ELYs proper instances
-ELY-getters, and ELY-existance check for ArealRoadMaintainer
-Tests for ArealRoadMaintainer/ELY trait, and fixed ELY objects

VIITE-3418 ELY definitions.

---

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectReservedPartDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala

…of ELYs for class RoadwaySection. In tests, too.

VIITE-3423 ArealRoadMaintainer to RoadwaySection

---

README.md

VIITE-3015 update README.md after sbt upgrade.

---

viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

- identifySplitsToHandle now filters out project links with null/0 linear location ids from the grouping logic to avoid the bug

VIITE-3372 Reverting new project links bug fix

---

viite-UI/manual/index.html

Viite 3514 fix manual table of contents scroll

---

.eslintrc.js
viite-UI/src/model/LocationSearch.js
viite-UI/src/model/NodeCollection.js
viite-UI/src/view/AdminPanel.js
viite-UI/src/view/FormCommon.js
viite-UI/src/view/NodeLayer.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/RoadAddressBrowserWindow.js
viite-UI/src/view/RoadAddressChangesBrowserWindow.js
viite-UI/src/view/RoadLayer.js

Grunt varoitukset ja virheet korjattu.

VIITE-3538 Fix Grunt warnings and error

---

viite-UI/src/less/site/global.less
viite-UI/src/view/TileMapCollection.js
viite-UI/src/view/TileMapSelector.js

Lisätty nappula vasempaan alareunaan, jolla voi ottaa taustakartan pois käytöstä. Responsiivisuus muutokset toisessa branchissä.

VIITE-3541 Add button to hide background map

---

gruntfile.js
viite-UI/src/model/LocationSearch.js
viite-UI/src/model/NodeCollection.js
viite-UI/src/view/AdminPanel.js
viite-UI/src/view/FormCommon.js
viite-UI/src/view/NodeLayer.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/RoadAddressBrowserWindow.js
viite-UI/src/view/RoadAddressChangesBrowserWindow.js
viite-UI/src/view/RoadLayer.js
viite-UI/src/view/navigationpanel/ProjectListModel.js

Projekti taulukko hyödyntää nyt toissijaista lajittelua päivämäärän mukaan, eli saman "arvoiset" tai "ryhmän" projektit lajitellaan siten että uusimmat projektit on ylempänä.

VIITE-3266 Add secondary sorting by createdDate to all project list sort methods

---

viite-UI/src/view/NodeLayer.js

Korjattu bugi, jossa solmu resettasi vanhalle paikalle, jos sitä yritti siirtää heti ennen/jälkeen kartan zoomausta. Samalla korjattu myös indentaatio popup logiikalle.

VIITE-3557 Fix node resetting when dragged before/after zoom

---

viite-UI/src/less/site/map-plugins.less
viite-UI/src/model/ApplicationModel.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/NodeForm.js
viite-UI/src/view/NodeLayer.js
viite-UI/src/view/RoadLayer.js
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala

Cherry pickattu solmun siirto muutokset ja firefox spinneri korjaus postgisiltä hotfixiä varten

Viite 3552 node drag hotfix

---

viite-UI/src/less/site/global.less
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/RoadLayer.js

Lisätty EVK mock data tien hoveriin

VIITE-3455 Add EVK to road extra info hover popup

---

viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/ComplementaryLinkDAO.scala
viite-backend/database/src/test/scala/fi/vaylavirasto/viite/dao/ComplementaryLinkDAOSpec.scala

- New ComplementaryLinkDAOSpec file added with tests
- Modified fetchByLinkIds to return empty list when fetched with empty linkIds

VIITE-3306 Add test cases for ComplementaryLinkDAO

---

viite-UI/src/view/ProjectForm.js

Tuodaan viimeisimmät muutokset tähänkin branchiin

VIITE-3587 Fix project validation after link change

---

viite-UI/src/utils/backend-utils.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectForm.js

Korjattu kadonnut numerointi toimenpide ja siirto toimenpide bugi, jossa syöttökentät eivät tulleet näkyviin sen jälkeen, kun ne oli piilotettu

Viiite 3613 fix project edit form

---

viite-UI/src/view/FormCommon.js
viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/JunctionDAO.scala
viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/JunctionDAOSpec.scala

Fix node menu

---

viite-UI/src/less/site/action-panel.less
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/navigationpanel/ProjectListModel.js
viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala

Lisätty EVK (Elinvoimakeskus) projektilistaan.

Viite-3628 Add EVK to project list
